hmrc/tenure-cost-and-trade-records-frontend

app/controllers/Form6010/AboutYourTradingHistoryController.scala
app/controllers/Form6010/PremisesLicenseConditionsController.scala
app/form/Form6010/AboutYourTradingHistoryForm.scala
app/form/Form6010/PremisesLicenseDetailsForm.scala
app/models/submissions/Form6010/AboutYourTradingHistory.scala
app/models/submissions/Form6010/PremisesLicenseInformationDetails.scala
app/views/Form6010/aboutTheProperty.scala.html
app/views/Form6010/aboutYou.scala.html
app/views/Form6010/aboutYourTradingHistory.scala.html
app/views/Form6010/enforcementActionBeenTaken.scala.html
app/views/Form6010/enforcementActionBeenTakenDetails.scala.html
app/views/Form6010/licensableActivities.scala.html
app/views/Form6010/licensableActivitiesDetails.scala.html
app/views/Form6010/premisesLicense.scala.html
app/views/Form6010/premisesLicenseConditions.scala.html
app/views/Form6010/tiedForGoods.scala.html
app/views/Form6010/tiedForGoodsDetails.scala.html
app/views/Form6010/websiteAddressForProperty.scala.html
app/views/Form6010/websiteForProperty.scala.html
app/views/connectionToTheProperty.scala.html
app/views/taskList.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/ConnectionToThePropertyControllerSpec.scala
test/controllers/form/PostcodeMappingSpec.scala

Also added tests to take over coverage limit

BST-38301 - Started adding backlink to forms and added missing forms to views

---

app/controllers/Form6010/TiedForGoodsController.scala

…erday! Replace if statement with case match

BST-41126 - Test to make sure push is still working after issues yesterday! Replace if statement with case match

---

app/controllers/aboutfranchisesorlettings/ConcessionOrFranchiseController.scala
app/navigation/AboutFranchisesOrLettingsNavigator.scala
app/views/aboutfranchisesorlettings/concessionOrFranchise.scala.html
conf/messages
conf/messages.cy
test/navigation/AboutFranchisesOrLettingsNavigatorSpec.scala

Also sorted apostrophe issues out on messages file

BST-46970 - Added navigation for new page and fixed failing test

---

app/models/SubmissionDraft.scala
conf/messages
conf/messages.cy
project/AppDependencies.scala
project/plugins.sbt

- Finalized models.SubmissionDraft

BST-46980 TCTR : Formulate the data structure for saving from frontend to backend

---

app/controllers/LoginController.scala
app/controllers/SaveAsDraftController.scala
app/form/SaveAsDraftLoginForm.scala
app/views/includes/continueSaveAsDraftButtons.scala.html
app/views/saveAsDraftLogin.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/LoginControllerSpec.scala
test/controllers/SaveAsDraftControllerSpec.scala

- saveAsDraftLogin.scala.html
- SaveAsDraftLoginForm
- Action `loginToResume`
- Action `resume`
- Action `startAgain`

BST-54984 TCTR Restoring from `SubmissionDraft`

---

app/models/submissions/aboutyouandtheproperty/CurrentPropertyUsed.scala
app/views/aboutyouandtheproperty/aboutTheProperty.scala.html
app/views/aboutyouandtheproperty/checkYourAnswersAboutTheProperty.scala.html
app/views/additionalinformation/checkYourAnswersAdditionalInformation.scala.html
app/views/includes/checkYourAnswersRadioButtons.scala.html
conf/messages
conf/messages.cy
test/views/aboutyouandtheproperty/CheckYourAnswersAboutThePropertyViewSpec.scala

- About you, About the property, Website address sections with `"Change"` links to edit value on corresponding page.
- Display property usage custom value if option `Other` is selected. 
- Hide Website address row if option `No` is selected.

BST-57034 Implement the about you and the property CYA page

---

app/assets/javascripts/show-password.js
app/controllers/FORDataCaptureController.scala
app/form/aboutyouandtheproperty/TiedForGoodsDetailsForm.scala
app/models/submissions/aboutyouandtheproperty/PremisesLicenseConditionsDetails.scala
app/models/submissions/aboutyouandtheproperty/TiedForGoodsInformationDetails.scala
app/util/SectionAnswers.scala
app/views/aboutyouandtheproperty/checkYourAnswersAboutTheProperty.scala.html
conf/messages
conf/messages.cy
test/util/SectionAnswersSpec.scala

- `Your license` CYA section
- `SectionAnswers` generic builder
- `SectionAnswersSpec` unit test

BST-57034 CYA about you and the property. `Your license`, `SectionAnswers`, `SectionAnswersSpec` unit test

---

app/controllers/aboutfranchisesorlettings/CheckYourAnswersAboutFranchiseOrLettingsController.scala
app/form/aboutfranchisesorlettings/CheckYourAnswersAboutFranchiseOrLettingsForm.scala
app/navigation/AboutFranchisesOrLettingsNavigator.scala
app/views/aboutfranchisesorlettings/checkYourAnswersAboutFranchiseOrLettings.scala.html
app/views/aboutyouandtheproperty/checkYourAnswersAboutTheProperty.scala.html
app/views/additionalinformation/checkYourAnswersAdditionalInformation.scala.html
app/views/includes/checkYourAnswersRadioButtons.scala.html
conf/messages
conf/messages.cy
test/controllers/aboutfranchisesorlettings/CheckYourAnswersAboutFranchiseOrLettingsControllerSpec.scala
test/views/aboutFranchisesOrLettings/CheckYourAnswersAboutFranchiseOrLettingsViewSpec.scala

- `AboutFranchisesOrLettingsNavigator`
- `CheckYourAnswersAboutFranchiseOrLettingsController`
- `CheckYourAnswersAboutFranchiseOrLettingsForm`
- Fixed layout of `checkYourAnswersRadioButtons`
- Updated unit tests

BST-57036 CYA - franchises or lettings

---

app/config/AppConfig.scala
app/views/Layout.scala.html
conf/messages

Use govukLayout, instead of hmrcLayout to add customFooter.
Added content in footer. Screenshot attached in JIRA.

BST-56024 Add contact details into the footer

---

app/controllers/connectiontoproperty/EditAddressController.scala
app/form/MappingSupport.scala
app/models/submissions/connectiontoproperty/EditAddress.scala
app/models/submissions/connectiontoproperty/EditAddressDetails.scala
app/models/submissions/connectiontoproperty/StillConnectedDetails.scala
app/views/connectiontoproperty/editAddress.scala.html
app/views/includes/radioButtons.scala.html
conf/messages
conf/messages.cy
test/controllers/connectiontoproperty/EditAddressControllerSpec.scala
test/utils/FakeObjects.scala
test/views/connectiontoproperty/EditAddressViewSpec.scala

…sue, as well as fixed BST-60903 in this ticket

BST-60903 - Changed edit address to match mural and fixed postcode issue, as well as fixed BST-60903 in this ticket

---

app/controllers/connectiontoproperty/VacantPropertiesController.scala
app/form/Formats.scala
app/form/MappingSupport.scala
app/form/connectiontoproperty/VacantPropertiesForm.scala
app/models/submissions/connectiontoproperty/StillConnectedDetails.scala
app/models/submissions/connectiontoproperty/VacantProperties.scala
app/models/submissions/connectiontoproperty/VacantPropertiesDetails.scala
app/navigation/ConnectionToPropertyNavigator.scala
app/navigation/identifiers/ConnectionToPropertyIdentifiers.scala
app/views/connectiontoproperty/vacantProperties.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/connectiontoproperty/VacantPropertiesControllerSpec.scala
test/utils/FakeObjects.scala
test/utils/FakeViews.scala
test/views/connectiontoproperty/VacantPropertiesViewSpec.scala

This is just a static page and not actually part of the journey yet, as other pages after need creating.

BST-60908 - Added vacant properties page and tests

---

app/controllers/notconnected/CheckYourAnswersNotConnectedController.scala

Fixed passing *language* parameter from TCTR frontend to backend on NotConnectedSubmission

BST-64959 Fixed passing `language` from frontend to backend

---

app/controllers/aboutfranchisesorlettings/AddAnotherCateringOperationController.scala
app/controllers/connectiontoproperty/VacantPropertiesController.scala
app/form/aboutfranchisesorlettings/AddAnotherCateringOperationOrLettingAccommodationForm.scala
app/views/connectiontoproperty/vacantProperties.scala.html
conf/messages
conf/messages.cy
test/controllers/aboutfranchisesorlettings/AddAnotherCateringOperationControllerSpec.scala
test/views/connectiontoproperty/VacantPropertiesViewSpec.scala

Also amended name on 'Add another catering operation' as per Sneha's request

BST-68758 - Resolved backlink issue for edit address and vacant property

---

app/controllers/connectiontoproperty/IsRentReceivedFromLettingController.scala

Fixed intermittent issue with `stillConnectedDetails.isAnyRentReceived` used for BackLink generation before it saved in session.

Fixed intermittent issue with saving `isAnyRentReceived`

---

app/views/aboutthetradinghistory/totalPayrollCosts.scala.html

BST-79102 totalPayrollCost responsive update.

---

app/controllers/aboutYourLeaseOrTenure/DoesRentIncludeParkingController.scala
app/controllers/aboutYourLeaseOrTenure/IncludedInRentParkingSpacesController.scala
app/controllers/aboutYourLeaseOrTenure/IsParkingRentPaidSeparatelyController.scala
app/controllers/aboutYourLeaseOrTenure/RentOpenMarketValueController.scala
app/controllers/aboutYourLeaseOrTenure/RentedEquipmentDetailsController.scala
app/controllers/aboutYourLeaseOrTenure/RentedSeparatelyParkingSpacesController.scala
app/form/MappingSupport.scala
app/form/aboutYourLeaseOrTenure/RentedEquipmentDetailsForm.scala
app/models/submissions/aboutYourLeaseOrTenure/AboutLeaseOrAgreementPartThree.scala
app/navigation/AboutYourLeaseOrTenureNavigator.scala
app/navigation/identifiers/AboutYourLeaseOrTenureIdenifiers.scala
app/views/aboutYourLeaseOrTenure/rentedEquipmentDetails.scala.html
conf/app.routes
conf/messages
conf/messages.cy
project/CodeCoverageSettings.scala
test/controllers/aboutYourLeaseOrTenure/RentedEquipmentDetailsControllerSpec.scala
test/navigation/AboutYourLeaseOrTenure6030NavigatorSpec.scala
test/utils/FakeObjects.scala
test/utils/FakeViews.scala

- Implemented new page `/rented-equipment-details`
- Updated forward & backward navigation for `/rent-include-fixtures-and-fittings`, `/rented-equipment-details` and linked pages

BST-88430 6020 - Add equipment details page to about the lease section

---

app/controllers/aboutthetradinghistory/Turnover6030Controller.scala

BST-88445 Do Not merge. Hotfix

---

app/controllers/aboutYourLeaseOrTenure/CurrentRentFirstPaidController.scala
app/controllers/aboutYourLeaseOrTenure/RentedEquipmentDetailsController.scala
app/controllers/aboutYourLeaseOrTenure/ThroughputAffectsRentController.scala
app/controllers/aboutYourLeaseOrTenure/ThroughputAffectsRentDetailsController.scala
app/form/aboutYourLeaseOrTenure/ThroughputAffectsRentDetailsForm.scala
app/form/aboutYourLeaseOrTenure/ThroughputAffectsRentForm.scala
app/models/submissions/aboutYourLeaseOrTenure/AboutLeaseOrAgreementPartThree.scala
app/models/submissions/aboutYourLeaseOrTenure/ThroughputAffectsRent.scala
app/models/submissions/aboutyouandtheproperty/AlternativeContactDetails.scala
app/navigation/AboutYourLeaseOrTenureNavigator.scala
app/navigation/identifiers/AboutYourLeaseOrTenureIdenifiers.scala
app/views/aboutYourLeaseOrTenure/throughputAffectsRent.scala.html
app/views/aboutYourLeaseOrTenure/throughputAffectsRentDetails.scala.html
conf/app.routes
conf/messages
conf/messages.cy
test/controllers/aboutYourLeaseOrTenure/ThroughputAffectsRentControllerSpec.scala
test/controllers/aboutYourLeaseOrTenure/ThroughputAffectsRentDetailsControllerSpec.scala
test/utils/BehaviourVerification.scala
test/utils/FakeObjects.scala
test/utils/FakeViews.scala
test/views/aboutthetradinghistory/FinancialYearEndDatesViewSpec.scala

- Created session model `ThroughputAffectsRent` in frontend and backend. Updated related lease objects and tests.
- Created forms `ThroughputAffectsRentForm`, `ThroughputAffectsRentDetailsForm` and validation error messages for new pages /throughput-affects-rent , /throughput-affects-rent-details
- Created new method to update session - `AboutLeaseOrAgreementPartThree.updateThroughputAffectsRent()`
- Implemented routes, forward & backward navigation, controller and page template for `/throughput-affects-rent`
- Implemented routes, forward & backward navigation, controller and page template for `/throughput-affects-rent-details`
- Added unit tests to achieve coverage beyond `82.0%`

BST-88058 Throughput affects rent - 6020 lease pages

---

app/views/includes/taskListItem.scala.html
app/views/taskList.scala.html
conf/messages
conf/messages.cy
project/CodeCoverageSettings.scala
test/controllers/TaskListSpec.scala

- Added 6076 Trading History section to TaskList
- Added 6076 TaskList unit test to achieve coverage beyond 85.1%

BST-91285 Added 6076 Trading History section to TaskList

---

app/controllers/lettingHistory/ResidentDetailController.scala
app/form/lettingHistory/ResidentDetailForm.scala
app/models/SensitiveSession.scala
app/models/submissions/lettingHistory/LettingHistory.scala
app/models/submissions/lettingHistory/ResidentDetail.scala
app/models/submissions/lettingHistory/SensitiveLettingHistory.scala
app/models/submissions/lettingHistory/SensitiveResidentDetail.scala
app/navigation/LettingHistoryNavigator.scala
app/views/lettingHistory/residentDetail.scala.html
conf/lettingHistory.routes
conf/messages
conf/messages.cy
test/controllers/lettingHistory/PermanentResidentsControllerSpec.scala
test/controllers/lettingHistory/ResidentDetailControllerSpec.scala
test/form/lettingHistory/PermanentResidentFormSpec.scala
test/form/lettingHistory/ResidentDetailFormSpec.scala
test/models/submissions/lettingHistory/SensitiveLettingHistorySpec.scala

BST-111688 Add 'Resident Detail' page

---

app/controllers/lettingHistory/PermanentResidentsController.scala
app/controllers/lettingHistory/ResidentDetailController.scala
app/controllers/lettingHistory/ResidentListController.scala
app/form/lettingHistory/PermanentResidentsForm.scala
app/form/lettingHistory/ResidentListForm.scala
app/models/SensitiveSession.scala
app/models/submissions/lettingHistory/LettingHistory.scala
app/models/submissions/lettingHistory/SensitiveLettingHistory.scala
app/navigation/LettingHistoryNavigator.scala
app/navigation/Navigator.scala
app/navigation/identifiers/LettingHistoryIdentifiers.scala
app/views/lettingHistory/permanentResidents.scala.html
app/views/lettingHistory/residentDetail.scala.html
app/views/lettingHistory/residentList.scala.html
conf/lettingHistory.routes
conf/messages
conf/messages.cy
test/controllers/lettingHistory/LettingHistorySpec.scala
test/controllers/lettingHistory/PermanentResidentFixture.scala
test/controllers/lettingHistory/PermanentResidentsControllerSpec.scala
test/controllers/lettingHistory/ResidentDetailControllerSpec.scala
test/controllers/lettingHistory/ResidentListControllerSpec.scala
test/form/lettingHistory/ResidentListFormSpec.scala
test/models/submissions/lettingHistory/LettingHistorySpec.scala
test/models/submissions/lettingHistory/SensitiveLettingHistorySpec.scala

BST-111694 Add 'Residents List' page

---

conf/messages

Confirmed with Allan that it was needed for all forms

BST-112374 - Added 'disregarded' to h1 for all forms

---

app/controllers/lettingHistory/CompletedLettingsController.scala
app/controllers/lettingHistory/FiscalYearSupport.scala
app/controllers/lettingHistory/OccupierDetailController.scala
app/controllers/lettingHistory/RentalPeriodController.scala
app/form/lettingHistory/FieldMappings.scala
app/form/lettingHistory/OccupierDetailForm.scala
app/form/lettingHistory/RentPeriodForm.scala
app/models/submissions/lettingHistory/LettingHistory.scala
app/models/submissions/lettingHistory/LocalPeriod.scala
app/models/submissions/lettingHistory/OccupierDetail.scala
app/models/submissions/lettingHistory/SensitiveLettingHistory.scala
app/models/submissions/lettingHistory/SensitiveOccupierDetail.scala
app/navigation/LettingHistoryNavigator.scala
app/navigation/identifiers/LettingHistoryIdentifiers.scala
app/views/lettingHistory/completedLettings.scala.html
app/views/lettingHistory/occupierDetail.scala.html
app/views/lettingHistory/rentalPeriod.scala.html
app/views/lettingHistory/residentList.scala.html
conf/lettingHistory.routes
conf/messages
conf/messages.cy
project/CodeCoverageSettings.scala
test/controllers/lettingHistory/CompletedLettingsControllerSpec.scala
test/controllers/lettingHistory/LettingHistoryControllerSpec.scala
test/controllers/lettingHistory/OccupierDetailControllerSpec.scala
test/controllers/lettingHistory/RentalPeriodControllerSpec.scala
test/form/lettingHistory/OccupierDetailFormSpec.scala
test/form/lettingHistory/RentalPeriodFormSpec.scala
test/models/submissions/lettingHistory/SensitiveLettingHistorySpec.scala

BST-112077 Add page 'Rent Period'

---

app/controllers/lettingHistory/CompletedLettingsController.scala
app/controllers/lettingHistory/OccupierDetailController.scala
app/controllers/lettingHistory/OccupierListController.scala
app/controllers/lettingHistory/RentalPeriodController.scala
app/controllers/lettingHistory/RentalPeriodSupport.scala
app/controllers/lettingHistory/ResidentDetailController.scala
app/form/lettingHistory/FieldMappings.scala
app/form/lettingHistory/OccupierListForm.scala
app/form/lettingHistory/RentPeriodForm.scala
app/models/submissions/lettingHistory/LettingHistory.scala
app/navigation/LettingHistoryNavigator.scala
app/navigation/identifiers/LettingHistoryIdentifiers.scala
app/views/lettingHistory/completedLettings.scala.html
app/views/lettingHistory/occupierDetail.scala.html
app/views/lettingHistory/occupierList.scala.html
conf/lettingHistory.routes
conf/messages
conf/messages.cy
test/controllers/lettingHistory/CompletedLettingsControllerSpec.scala
test/controllers/lettingHistory/OccupierDetailControllerSpec.scala
test/controllers/lettingHistory/OccupierListControllerSpec.scala
test/controllers/lettingHistory/PermanentResidentsControllerSpec.scala
test/controllers/lettingHistory/RentalPeriodControllerSpec.scala
test/controllers/lettingHistory/ResidentDetailControllerSpec.scala
test/form/lettingHistory/OccupierListFormSpec.scala
test/form/lettingHistory/RentalPeriodFormSpec.scala

BST-112081 Add page _“You have added N temporary occupiers (change/remove)”_ 

---

app/controllers/lettingHistory/RentalPeriodController.scala
app/views/lettingHistory/occupierList.scala.html
app/views/lettingHistory/residentList.scala.html
test/controllers/lettingHistory/RentalPeriodControllerSpec.scala

Resolves: BST-114019, BST-114021, BST-114031

Handle maximum number of occupiers

---

app/controllers/aboutthetradinghistory/EditFinancialYearEndDateController.scala
app/controllers/aboutthetradinghistory/FinancialYearEndController.scala
app/models/submissions/aboutthetradinghistory/AboutTheTradingHistoryPartOne.scala
app/models/submissions/aboutthetradinghistory/OccupationalAndAccountingInformation.scala
app/navigation/AboutTheTradingHistoryNavigator.scala
app/views/aboutthetradinghistory/financialYears.scala.html
app/views/aboutthetradinghistory/turnover.scala.html
app/views/answers/answersAboutYourTradingHistory.scala.html
project/CodeCoverageSettings.scala
test/controllers/aboutthetradinghistory/FinancialYearEndControllerSpec.scala
test/controllers/aboutthetradinghistory/FinancialYearEndDatesSummaryControllerSpec.scala
test/navigation/AboutTheTradingHistoryNavigatorSpec.scala
test/views/aboutthetradinghistory/TurnoverViewSpec.scala

This is done for Form of Returns 6010, 6011, 6015 and 6016

BST-118923 Add warning page about financial year updates

---

app/navigation/AboutYourLeaseOrTenureNavigator.scala
app/views/aboutyouandtheproperty/contactDetailsQuestion.scala.html
app/views/aboutyouandtheproperty/partsUnavailable.scala.html
app/views/answers/answersAboutTheProperty.scala.html
conf/messages
conf/messages.cy

BST-120858 - Added Welsh for some 6048 pages

---

conf/messages

BST-125499 - Amended wording for lettings

---

.scalafmt.conf
app/assets/stylesheets/app.min.scss
app/views/Layout.scala.html
app/views/answers/AnswersAboutRentalIncomeHelpers.scala
app/views/includes/account_info_header.scala.html
conf/application.conf
project/CodeCoverageSettings.scala

- https://docs.google.com/document/d/1Xx9A6VfWuYDI_McQ-b1qF6j2x99WOZpT6ioRs2AoAXc/edit?tab=t.0
- https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=1083801997
- [#event-govuk-rebrand](https://hmrcdigital.slack.com/archives/C08R64APU00)

BST-132828 Implement new `GOV.UK rebrand` across service UI
